apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-team-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prathyushreddy123/enterprise-multitenant-gitops
    targetRevision: HEAD
    path: tenants/microservices-team/helm-release-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
