replicaCount: 1

image:
  repository: gcr.io/google-samples/microservices-demo/emailservice
  tag: v0.8.0

service:
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
