replicaCount: 1
image:
  repository: gcr.io/google-samples/microservices-demo/loadgenerator
  tag: v0.8.0
service:
  port: 8080
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
