replicaCount: 1
image:
  repository: gcr.io/google-samples/microservices-demo/shippingservice
  tag: v0.8.0
service:
  port: 50051
resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
