replicaCount: 1

image:
  repository: gcr.io/google-samples/microservices-demo/cartservice
  tag: v0.8.0

service:
  port: 7070

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
