apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: common
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      type: Container
