apiVersion: v1
kind: ResourceQuota
metadata:
  name: common-quota
  namespace: common
spec:
  hard:
    pods: "100"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
