replicaCount: 1

image:
  repository: gcr.io/google-samples/microservices-demo/productcatalogservice
  tag: v0.8.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3550

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
